// Looks like most of the name have a specific structure:
// * xxxthorpe
// * xxxton
// * xxxby
// * xxxborough
// * Little xxx
// * South/East/West/North xxx
// * xxx-upon-yyy
// * xxx near yyy
// * St. xxx
//
// See https://en.m.wikipedia.org/wiki/List_of_generic_forms_in_place_names_in_the_United_Kingdom_and_Ireland
//
// This means we could change this into a specific form generator similar to
// how the `Gravedigger` module works, selecting a specified structure and then
// filling the variable parts with Markov-generated words.

export let townNames = [
  'Abergravenny',
  'Aldwick',
  'Appletree',
  'Apuldram',
  'Badbea',
  'Badby',
  'Baggrave',
  'Berehill',
  'Bingham',
  'Binnend',
  'Bishop\'s Fee',
  'Boreraig',
  'Botolph Bridge',
  'Bradgate',
  'Brentingby',
  'Brooksby',
  'Burgh',
  'Carburton',
  'Carnarvon',
  'Churchfield',
  'Clapcot',
  'Clipston',
  'Clopton',
  'Cottons',
  'Cratendune',
  'Crofton',
  'Cudlow',
  'Dormill',
  'Doveland',
  'East Itchenor',
  'East Matfen',
  'East Shefford',
  'Eastmill',
  'Exceat',
  'Farnham',
  'Findhorn',
  'Flexmere',
  'Freybridge',
  'Frogmire',
  'Gainsthorpe',
  'Garendon',
  'Gilston',
  'Glanyfaron',
  'Glenbuck',
  'Hainstone',
  'Hampton-on-sea',
  'Hanstead',
  'Hawkshaw',
  'Hodenhoe',
  'Hound Tor',
  'Ingarsby',
  'Kersey',
  'Keythorpe',
  'Kilpeck',
  'Kinwick',
  'Kirby',
  'Kitts End',
  'Knapthorpe',
  'Langley',
  'Leesthorpe',
  'Little Creaton',
  'Little Oxendon',
  'Longton',
  'Lordington',
  'Lower Catesby',
  'Lowton',
  'Luffnum',
  'Maidencourt',
  'Martinsthorpe',
  'Napsbury',
  'Nobold',
  'Northwick',
  'Odstone',
  'Orgarswich',
  'Osberton',
  'Osgodby',
  'Oston',
  'Othorpe',
  'Otterburn',
  'Oxwich near Codicote',
  'Pangdean',
  'Parham',
  'Pendley',
  'Penterry',
  'Phoside',
  'Pipewell',
  'Potcote',
  'Preston Deanery',
  'Scarborough',
  'Shadowbridge',
  'Sheep Lane',
  'Shirtecoat',
  'Shuart',
  'Silvermeadow',
  'Snave',
  'Southorpe',
  'St. Kilda',
  'Stapleford',
  'Stonebury',
  'Thorley',
  'Tugby',
  'Wacton',
  'Wakeley',
  'Wayford',
  'Welbeck',
  'Wellbury',
  'Westwilde',
  'Wharram Percy',
  'Whitwell',
  'Wolferlow',
  'Woodgate',
];
