export const MAX_AGE = 65;
export const MAX_AGE_DIFFERENCE_TO_MARRY = 10;
export const MINIMUM_AGE_TO_MARRY = 17;
export const NATURAL_DISASTER_CHANCE = 0.05;
export const PROBABILITY_TO_BREED = 0.2;
export const PROBABILITY_TO_MARRY = 0.99999999999;
